expressive-code/expressive-code

packages/@expressive-code/plugin-text-markers/src/styles.ts
Hi there! It's maybe a bit early to contribute, but anyways, I'll try my luck 😅
When marking substrings of code blocks, the `.ec-line mark::before` prevents the user from selecting the underlying text. Adding `pointer-events: none` fixes this.
=> Make marked text selectable

.changeset/odd-grapes-sell.md, packages/@expressive-code/plugin-frames/src/copy-js-module.ts
Adds support for dynamically added copy buttons to `@expressive-code/plugin-frames`.
In addition to initializing all copy buttons that exist on the page when first loading the JS module, the new code now also registers a `MutationObserver` to handle any new buttons added later.
This should fix non-working copy buttons in cases when the page dynamically loads more content or replaces existing content (e.g. SPA scenarios as reported in #16).
=> Fix non-working copy buttons in dynamic content

.changeset/polite-crews-applaud.md, packages/@expressive-code/core/README.md, packages/@expressive-code/core/src/common/core-styles.ts, packages/@expressive-code/core/src/common/engine.ts, packages/@expressive-code/plugin-frames/README.md, packages/@expressive-code/plugin-shiki/README.md, packages/@expressive-code/plugin-text-markers/README.md, packages/astro-expressive-code/README.md, packages/expressive-code/README.md, packages/remark-expressive-code/README.md, packages/remark-expressive-code/test/remark.test.ts
Addresses #18 by adding the config options `useThemedScrollbars` and `useThemedSelectionColors`.
Both options default to `true`. Set any of them to `false` to prevent themes from customizing their appearance and render them using the browser's default style.
=> Allow disabling themed scrollbars and selections

.changeset/young-beers-attend.md, packages/@expressive-code/plugin-text-markers/README.md, packages/@expressive-code/plugin-text-markers/src/index.ts, packages/@expressive-code/plugin-text-markers/test/data/diff-examples.ts, packages/@expressive-code/plugin-text-markers/test/rendering.test.ts
=> Add support for `diff`-like syntax and `lang` meta attribute

.changeset/olive-bikes-shout.md, packages/@expressive-code/plugin-frames/src/styles.ts
This PR tweaks the styles for the three dots shown top left in terminal frames in the frames plugin. Instead of using an SVG for the `content` of the pseudo-element, it uses the SVG as a `mask-image` instead. This lets us set the colour with a CSS custom property (or other complex value such as a gradient), which is not permitted in data URL images as they are treated as external images (which don’t have access to document-scope values such as custom properties or keywords like `currentColor`.
A user could now set a style override like this and have it work:
```js
terminalTitlebarDotsForeground: 'var(--my-accent-color)',
```
Or even to mimic macOS style close/minimise/zoom colours:
```js
terminalTitlebarDotsForeground: 'linear-gradient(to right, red 33%, yellow 33%, yellow 66%, green …
```
=> Support CSS variable colour as terminal dots foreground

.changeset/good-suns-hug.md, packages/@expressive-code/plugin-frames/README.md, packages/@expressive-code/plugin-frames/src/index.ts, packages/@expressive-code/plugin-frames/test/copy-button.test.ts
Closes #41 by adding a new `removeCommentsWhenCopyingTerminalFrames` config option to `plugin-frames`. Thanks @AkashRajpurohit!
If `true` (which is the default), the "Copy to clipboard" button of terminal window frames will remove comment lines starting with `#` from the copied text.
This is useful to reduce the copied text to the actual commands users need to run, instead of also copying explanatory comments or instructions.
=> Add `removeCommentsWhenCopyingTerminalFrames`

.changeset/green-flies-burn.md, packages/@expressive-code/core/src/common/engine.ts, packages/@expressive-code/core/src/internal/render-group.ts, packages/astro-expressive-code/README.md, packages/astro-expressive-code/src/index.ts, packages/astro-expressive-code/test/fixtures/astro/astro.config.mjs, packages/astro-expressive-code/test/fixtures/astro/src/layouts/MainLayout.astro, packages/astro-expressive-code/test/fixtures/astro/src/pages/index.md, packages/astro-expressive-code/test/fixtures/astro/src/pages/mdx-page.mdx, packages/astro-expressive-code/test/integration.test.ts, packages/remark-expressive-code/README.md, packages/remark-expressive-code/src/index.ts
Closes #36 by adding multi-theme support to the `theme` config option.
You can now pass an array of themes to the `theme` config option of `remark-expressive-code` and `astro-expressive-code`.
This allows you to render each code block in your markdown/MDX documents using multiple themes, e.g. to support light and dark modes on your site.
**Note**: If you use this feature, you will also need to add custom CSS code to your site to ensure that only one theme is visible at any time.
To allow targeting all code blocks of a given theme through CSS, the theme property `name` is used to generate kebap-cased class names in the format `ec-theme-${name}`. For example, `theme: ['monokai', 'slack-ochin']` will render every code block twice, once with the class `ec-theme-monokai`, and once with …
=> Add multi-theme support to `theme` config option

.changeset/chatty-doors-float.md, packages/@expressive-code/plugin-collapsible-sections/src/styles.ts
Safari doesn't support `content` for `::marker` pseudo-element. See https://bugs.webkit.org/show_bug.cgi?id=204163
Workaround using non-standard pseudo-element.
Addresses comment: https://github.com/expressive-code/expressive-code/pull/50/files#r1299367415
=> Hide summary marker for collapsible section on Safari

.changeset/slow-zoos-teach.md, packages/@expressive-code/plugin-frames/src/copy-js-module.ts
Fixes #70 by adding an event handler for Astro view transitions.
=> Re-initialize copy to clipboard buttons after Astro view transitions

.changeset/young-beans-reflect.md, internal/test-utils/src/html-snapshots.ts, packages/@expressive-code/plugin-text-markers/src/inline-markers.ts, packages/@expressive-code/plugin-text-markers/test/rendering.test.ts
Fixes #73.
The logic inside `flattenInlineMarkerRanges` had a flaw that caused various combinations of `mark`, `ins` and `del` inline markers on the same line to fail. This was fixed and more tests were added.
=> Fix multiple inline marker types on the same line

.changeset/short-phones-tell.md, packages/astro-expressive-code/src/index.ts, packages/astro-expressive-code/test/integration.test.ts
Temporarily disable new `emitExternalStylesheet` option again due to a route resolution bug.
Sadly, this bug didn't occur before actually publishing the package - it worked fine when linking the package locally. Insert sad trombone sound here.
=> Temp disable `emitExternalStylesheet` due to a bug

.changeset/few-donuts-wait.md, packages/@expressive-code/plugin-frames/src/utils.ts, packages/@expressive-code/plugin-frames/test/preprocess-code.test.ts
Addresses https://github.com/withastro/starlight/issues/1158 by adding rules that prevent comments like `// ...` from being incorrectly detected as file names. Thanks @kdheepak!
=> Fix unexpected file name comment detections

docs/src/content/docs/plugins/collapsible-sections.mdx
Adding the collapsible sections plugin to a Starlight project works a bit differently from adding the plugin to a vanilla Astro project. Similar to the `Installation` page this PR adds additional documentation on how to add the plugin to a Starlight project.
=> Docs: Add documentation on how to add the collapsible sections plugin to a Starlight project

.changeset/chilled-lizards-tap.md, docs/src/content/docs/reference/core-api.mdx, internal/test-utils/package.json, internal/test-utils/src/color-contrast.ts, internal/test-utils/src/index.ts, packages/@expressive-code/core/src/common/annotation.ts, packages/@expressive-code/core/src/common/engine.ts, packages/@expressive-code/core/src/common/theme.ts, packages/@expressive-code/core/src/helpers/color-transforms.ts, packages/@expressive-code/plugin-text-markers/src/index.ts, packages/@expressive-code/plugin-text-markers/test/data/marker-examples.ts, packages/@expressive-code/plugin-text-markers/test/rendering.test.ts, pnpm-lock.yaml
Improves automatic color contrast correction when using CSS variables in styleOverrides. Fixes #144. Thanks @heycassidy!
This PR makes it possible to use CSS variables in the `styleOverrides` setting `codeBackground` without negatively affecting the automatic color contrast correction controlled by the `minSyntaxHighlightingColorContrast` setting.
If a CSS variable is encountered that cannot be resolved to a color value on the server, Expressive Code now automatically uses the theme's background color as a fallback for color contrast calculations. You can also provide your own fallback color using the CSS variable fallback syntax, e.g. `var(--gray-50, #f9fafb)`.
=> Fix color contrast correction when using CSS variables

.changeset/tough-pandas-prove.md, packages/astro-expressive-code/src/index.ts
This brings us another step closer to fixing #108, but we're still waiting for a full fix within Astro core that actually adds support for prerendering injected `.ts` routes.
=> Add `prerender: true` to injected routes

.changeset/stupid-keys-reflect.md, packages/@expressive-code/core/src/helpers/color-transforms.ts
Cloning `TinyColor` using an object instead of a string is faster as `TinyColor` doesn't have to guess the format of the string on init.
- https://github.com/scttcper/tinycolor/blob/64270d80c1287355c6c9f719baa6777d5eac3ee5/src/format-input.ts#L122
- https://github.com/scttcper/tinycolor/blob/64270d80c1287355c6c9f719baa6777d5eac3ee5/src/format-input.ts#L46-L48
Locally, this drops the execution time of `toTinyColor` from 2.55s to 2.06s:
=> Clone TinyColor with toRgb

.changeset/friendly-bats-drop.md, packages/@expressive-code/core/package.json, pnpm-lock.yaml
Updated dependencies for `@expressive-code/core` (except `shiki` so the version is the same with other packages).
This also bumps the major of `@ctrl/tinycolor` and `culori`. Seems like their breaking changes shouldn't affect us. The main reason I sent this PR is to bump `@ctrl/tinycolor` so I can get https://github.com/scttcper/tinycolor/pull/251 in. I figured to update the rest of the dependencies along the way.
Let me know if you want to do the upgrades differently or if this is silly 😄 Happy to close this if so.
=> Update dependencies for `@expressive-code/core`

.changeset/quick-dragons-cover.md, packages/@expressive-code/plugin-frames/src/utils.ts, packages/@expressive-code/plugin-frames/test/preprocess-code.test.ts
**Changes**
* Modifies file name regex string to include + in file names
* Added tests to cover +layout.svelte use case
Resolves #204 
**Context**
File name comments were not processing as titles for SvelteKit file names like `+layout.svelte` and `+page.server.ts`.
=> Fix `plugin-frames` not processing commented file names containing `+` as titles

.changeset/friendly-pans-lay.md, packages/@expressive-code/plugin-shiki/src/index.ts, packages/@expressive-code/plugin-shiki/src/transformers.ts, packages/@expressive-code/plugin-shiki/test/rendering.test.ts
This adds 2 new options for the shiki plugin:
1. `includeExplanation` is passed on to shiki. It does not change EC's output at all, but might be required by transformers
2. `tokensTransformers` is a list of functions, matching the API of Shiki's `tokens` hook, that can manipulate Shiki's ThemedTokens before they are used to produce EC annotations
- transformers that edit the underlying text are not supported
For more background, see #234
=> Add transformers option to shiki plugin

.changeset/wise-snakes-turn.md, packages/astro-expressive-code/src/vite-plugin.ts
In Astro 4.15, the `command` type in the `astro:config:setup` hook was updated to also include `'sync'` as a possibility. This causes a type error when building EC with this version of Astro (see [this ecosystem CI failure](https://github.com/withastro/astro-ecosystem-ci/actions/runs/10627116283)), because EC includes an expectation that `command` does not include `'sync'`.
This PR updates that code to use the `HookParameters` utility type to get the `command` type for the current Astro version. This utility was added in Astro v1.0.0-beta.60 (source PR: https://github.com/withastro/astro/pull/3706), so is safe to use for EC’s peer dependency range of astro@^3.3.0.
=> Use Astro helper for hook type

.changeset/tidy-planes-smash.md, docs/src/components/PackageManagers.astro, packages/@expressive-code/plugin-frames/test/copy-button.test.ts, packages/@expressive-code/plugin-frames/test/rendering.test.ts
The pnpm official documentation recommends using the `add` command instead of `install` when installing new packages as follows:
- https://pnpm.io/cli/add
- https://pnpm.io/cli/install
Currently it works the same without any differences, but the document clearly distinguishes these two commands.
This means that you have the flexibility to adapt to changes, such as changing or removing commands in future versions.
=> Replace `pnpm i` with `pnpm add`

packages/@expressive-code/plugin-line-numbers/src/index.ts
Marking line gutters `aria-hidden` to make some scrapers and RSS readers happy.
=> Make rendered line number `aria-hidden`

docs/astro.config.mjs, docs/package.json, docs/src/content/docs/plugins/community-plugins.mdx, pnpm-lock.yaml
This PR adds a new “Community Plugins” page to the Expressive Code docs to showcase plugins and help users find more possibilities.
I added HiDeoo’s [`starlight-showcases`](https://starlight-showcases.vercel.app/) package to simplify adding this page, but can also do it with plain Starlight components if you prefer. The main benefit of the package is it abstracts away the grid and link cards so that maintaining the page only involves updating data.
Direct link to the page deploy preview: https://deploy-preview-259--expressive-code.netlify.app/plugins/community-plugins/
=> Add community plugins showcase to docs

.changeset/tender-camels-smoke.md, docs/scripts/lib/changelogs.ts, docs/src/content/docs/key-features/frames.mdx, docs/src/content/docs/reference/plugin-api.mdx, docs/src/content/docs/releases.md, packages/@expressive-code/core/src/common/engine.ts, packages/@expressive-code/core/src/common/plugin-style-settings.ts, packages/@expressive-code/core/src/common/style-settings.ts, packages/@expressive-code/core/src/index.ts, packages/@expressive-code/core/src/internal/css.ts, packages/@expressive-code/plugin-collapsible-sections/src/index.ts, packages/@expressive-code/plugin-collapsible-sections/src/styles.ts
Fixes #222.
Fixes #264.
This fixes invalid CSS file links when using the `Code` component together with `plugin-collapsible-sections` and `pnpm`. Due to the module resolution logic when using `pnpm`, the `Code` component was not able to access CSS variable replacements defined by the collapsible sections plugin.
=> Fix `cssVarReplacements` desync by moving it into `PluginStyleSettings`

.changeset/soft-frogs-sit.md, .changeset/twenty-coats-design.md, packages/astro-expressive-code/components/Code.astro, packages/astro-expressive-code/components/renderer.ts, packages/rehype-expressive-code/src/index.ts
Fixes #216.
Also fixes an issue where the optional `getBlockLocale` callback function was not called when using the `<Code>` component.
=> Fix `getBlockLocale` and `tabWidth` differences between `<Code>` and rehype

.changeset/cool-spies-applaud.md, packages/@expressive-code/core/src/internal/core-styles.ts, packages/@expressive-code/plugin-frames/src/styles.ts
Fixes #292. This moves the CSS rule that was previously a part of the core package into `plugin-frames` so that it can be conditionally included only when the copy to clipboard button is enabled.
The rule is meant to ensure that code overlapped by the copy button can be scrolled to make it visible, so it's unnecessary if the button is disabled.
=> Remove first line end padding if copy button is disabled

.changeset/rare-monkeys-sell.md, packages/@expressive-code/core/src/internal/core-styles.ts
Fixes #304. Now, not only `path` elements, but all SVGs and their contents are excluded from the reset.
=> Exclude all SVGs and children from style reset

.changeset/cuddly-drinks-doubt.md, .changeset/fair-games-hunt.md, .changeset/silver-hounds-hear.md, docs/scripts/api-reference.ts, docs/scripts/typedoc/templates/reference/core-api.mdx, docs/src/content/docs/key-features/frames.mdx, docs/src/content/docs/plugins/collapsible-sections.mdx, docs/src/content/docs/reference/core-api.mdx, packages/@expressive-code/core/src/helpers/assets.ts, packages/@expressive-code/core/src/index.ts, packages/@expressive-code/plugin-collapsible-sections/src/styles.ts, packages/@expressive-code/plugin-frames/src/styles.ts, packages/@expressive-code/plugin-shiki/src/index.ts, packages/@expressive-code/plugin-shiki/src/transformers.ts
Fixes #300 by adding a new utility function for inlining SVGs and updating the frames & collapsible sections plugins to support custom SVG icons:
- Adds the exported function `createInlineSvgUrl`, which creates an inline SVG image data URL from an SVG string (the contents of an SVG file). It can be used to embed SVG images directly into plugin styles or HAST, or pass them to a `styleOverrides` icon setting.
- Adds the following new `styleOverrides` settings:
- `frames.copyIcon`: Allows overriding the SVG icon used for the copy button.
- `frames.terminalIcon`: Allows overriding the SVG icon used for the terminal window frame. Defaults to three dots in the top left corner.
- `collapsibleSections.expandIcon` and `collapsibleSections.collapseIcon`: Allows overriding the SVG icons used for the …
=> Allow customizing SVG icons of frames & collapsible sections

.changeset/nine-cows-give.md, docs/src/content/docs/key-features/word-wrap.mdx, docs/src/content/docs/reference/configuration.mdx, packages/@expressive-code/core/src/common/block.ts, packages/@expressive-code/core/src/internal/render-block.ts
Fixes #282.
Adds a new `hangingIndent` prop to all code blocks. By setting this prop to a positive number of columns (either in the opening code fence, as a prop on the `<Code>` component, or in the `defaultProps` config option), you can now further refine the indentation of wrapped lines.
If the prop `preserveIndent` is `true` (which is the default), the `hangingIndent` value is added to the indentation of the original line. If `preserveIndent` is `false`, the value is used as the fixed indentation level of all wrapped lines.
This option only affects how the code block is displayed and does not change the actual code. When copied to the clipboard, the code will still contain the original unwrapped lines.
=> Add `hangingIndent` prop to code blocks

packages/astro-expressive-code/test/integration.test.ts
Fixes ecosystem CI test failure due to increased Astro bundle size (likely caused by Zod now being part of the bundle)
=> Bump allowed bundle size
